"""Generate the 4-cell counterbalanced pairwise block from explicit context contrasts.

A contrast names two specific values of one dimension to pit against each other
(e.g. provenance "ai_claude" vs "human_unknown"), defined in
data/context_contrasts.jsonl -- not hardcoded here. For a story pair
{story_1, story_2}, build_contrast_block() crosses BOTH:

- "assignment": which contrast value each story is attributed
  ("forward": story_1 gets value "a", story_2 gets value "b"; "flipped": the
  reverse), and
- "position": which story is DISPLAYED as Story A ("story1_as_a" or
  "story2_as_a")

into 4 cells sharing one block_id. An earlier version held position fixed
(story_1 was always Story A) and only varied assignment -- that isolates
context sensitivity from story identity, but leaves display position fully
confounded with story identity, so it can't separate a context-assignment
effect from a raw display-position effect. Crossing both factors makes them
separable: cells 1/2 share one context assignment and differ only in
position; cells 3/4 share the other assignment and also differ only in
position.

Both stories always carry some context (never nothing) in every cell -- the
control comes from swapping which value each story gets, not from comparing
against an empty baseline.

The contextual attribution is woven into a single deterministic opening
sentence (each contrast supplies its own "a_clause"/"b_clause" wording, hand
-written, not generated by an LLM) rather than posted as a label above each
story block -- see context_comparisons.INSTRUCTION_TEMPLATE.

Reuses context_comparisons.build_prompt() and its INSTRUCTION_TEMPLATE for the
actual prompt text (the existing natural "help me choose" / A-B-tie JSON
format) rather than duplicating it. Does not modify prompts.py, comparisons.py,
make_trials.py, run_trial.py, run_batch.py, analyze.py, or data/trials.jsonl,
and makes no API calls.

Run this file directly to print every cell's prompt in full, plus a summary
table of each contrast's per-cell intro sentences.
"""

import json

from context_packets import load_dimensions
from context_comparisons import build_prompt, load_items, load_story

CONTRASTS_FILE = "data/context_contrasts.jsonl"


def load_contrasts(path=CONTRASTS_FILE):
    """Read data/context_contrasts.jsonl into a list of contrast dicts."""
    contrasts = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                contrasts.append(json.loads(line))
    return contrasts


def assert_no_shared_identity_contradiction(dimensions, contrast):
    """Refuse contrasts that would make one claimed identity contradict itself.

    A two-story prompt has a single "I" speaking for both stories at once. Any
    dimension that depends_on another dimension (currently just writer_status,
    which depends on provenance) describes a property of *the person*, not of
    the individual story -- so it cannot validly take two different values
    across Story A and Story B in the same prompt, no matter what carrier is
    used: "I am a published author" for Story A and "this is my first time
    writing" for Story B contradict each other, since they're both said by the
    same "I" in the same breath.

    Dimensions like this are single-story only (see context_single_prompts.py,
    where each API call only ever claims one identity for one story).
    """
    dim = dimensions[contrast["dimension"]]
    if dim.get("depends_on"):
        raise ValueError(
            f"Contrast {contrast['id']!r} uses dimension {contrast['dimension']!r}, which "
            f"depends on {dim['depends_on']!r}. Dependent dimensions describe a claimed "
            f"identity shared by both stories in a two-story prompt, so they can't be "
            f"contrasted across Story A/B without contradicting themselves. Use "
            f"context_single_prompts.py for this dimension instead."
        )


def assert_values_are_registered(dimensions, contrast):
    """Sanity-check that a contrast's "a"/"b" values are real, registered dimension values.

    The intro sentence uses the contrast's own a_clause/b_clause wording, not
    context_dimensions.jsonl's phrasing -- this check exists purely to catch
    typos (an "a"/"b" that doesn't match anything in context_dimensions.jsonl),
    not to render text.
    """
    dim = dimensions[contrast["dimension"]]
    for value_id in (contrast["a"], contrast["b"]):
        if value_id not in dim["values"]:
            raise ValueError(
                f"Contrast {contrast['id']!r} references unknown value {value_id!r} "
                f"for dimension {contrast['dimension']!r}"
            )


def intro_sentence(first_clause, second_clause):
    """Build the deterministic opening sentence naming Story A's and Story B's attribution."""
    return (
        f"Hi! Can you give me some feedback on these two stories? "
        f"Story A {first_clause}, while Story B {second_clause}. "
        f"I'm trying to make up my mind."
    )


def build_contrast_block(dimensions, contrast, story_1, story_2, evaluation_regime):
    """Build the full 4-cell counterbalanced block for one contrast, across two
    different stories: story_1 and story_2 are the pair's fixed identities,
    crossed with BOTH of:

      - "assignment": which contrast value each story is attributed --
        "forward" (story_1 gets value "a", story_2 gets value "b") or
        "flipped" (story_1 gets value "b", story_2 gets value "a");
      - "position": which story is DISPLAYED as Story A -- "story1_as_a" or
        "story2_as_a".

    evaluation_regime ("naturalistic" or "text_only_invariance", see
    context_comparisons.INSTRUCTION_TEMPLATES) is a third, independent
    factor: it selects which evaluation instruction is used, but never
    changes the contextual framing/intro sentence itself, so the same
    contextual manipulation can be compared under both regimes. It's baked
    into block_id/trial_id so the two regimes' cells never collide.

    Earlier versions of this function held position fixed (story_1 was
    always Story A) and only varied assignment. That isolates context
    sensitivity from story identity, but leaves display position fully
    confounded with story identity (story_1 is always shown in position A),
    so it can't separate a context-assignment effect from a raw
    display-position effect. Crossing both factors gives 4 cells instead of
    2, sharing one block_id, so the two effects are separable:

        cell 1: assignment=forward, position=story1_as_a -> A=story_1(a), B=story_2(b)
        cell 2: assignment=forward, position=story2_as_a -> A=story_2(b), B=story_1(a)
        cell 3: assignment=flipped, position=story1_as_a -> A=story_1(b), B=story_2(a)
        cell 4: assignment=flipped, position=story2_as_a -> A=story_2(a), B=story_1(b)

    Cells 1/2 share one context assignment (story_1=a, story_2=b) and differ
    only in display position; cells 3/4 share the other assignment and also
    differ only in position. Every cell carries story_1_id/story_2_id (the
    pair's fixed identities, for grouping a block regardless of display
    position) alongside story_a_id/story_b_id (which story is actually shown
    in which position for this cell).
    """
    if story_1["id"] == story_2["id"]:
        raise ValueError("build_contrast_block requires two different stories, not the same story twice")

    assert_no_shared_identity_contradiction(dimensions, contrast)
    assert_values_are_registered(dimensions, contrast)

    text_1 = load_story(story_1["path"])
    text_2 = load_story(story_2["path"])
    pair_id = f"{story_1['id']}_vs_{story_2['id']}"
    block_id = f"block__{contrast['id']}__{pair_id}__{evaluation_regime}"
    a_clause, b_clause = contrast["a_clause"], contrast["b_clause"]

    # assignment -> (story_1's value/clause, story_2's value/clause)
    assignments = {
        "forward": ((contrast["a"], a_clause), (contrast["b"], b_clause)),
        "flipped": ((contrast["b"], b_clause), (contrast["a"], a_clause)),
    }
    stories = {"story1_as_a": (story_1, story_2, text_1, text_2), "story2_as_a": (story_2, story_1, text_2, text_1)}

    cells = []
    for assignment, (context_1, context_2) in assignments.items():
        for position, (story_a, story_b, text_a, text_b) in stories.items():
            context_by_id = {story_1["id"]: context_1, story_2["id"]: context_2}
            value_a, clause_a = context_by_id[story_a["id"]]
            value_b, clause_b = context_by_id[story_b["id"]]
            intro = intro_sentence(clause_a, clause_b)
            cells.append(
                {
                    "trial_id": f"{block_id}__{assignment}__{position}",
                    "block_id": block_id,
                    "contrast_id": contrast["id"],
                    "dimension": contrast["dimension"],
                    "story_1_id": story_1["id"],
                    "story_2_id": story_2["id"],
                    "story_a_id": story_a["id"],
                    "story_b_id": story_b["id"],
                    "assignment": assignment,
                    "position": position,
                    "evaluation_regime": evaluation_regime,
                    "context_a": {"value": value_a, "clause": clause_a},
                    "context_b": {"value": value_b, "clause": clause_b},
                    "intro": intro,
                    "prompt": build_prompt(intro, text_a, text_b, evaluation_regime),
                }
            )
    return cells


def main():
    dimensions = load_dimensions()
    contrasts = load_contrasts()
    items = load_items()
    story_1, story_2 = items[0], items[1]  # a fixed, distinct pair keeps the example small
    evaluation_regime = "naturalistic"  # preview one regime; see context_trials.py for both

    all_trials = []
    for contrast in contrasts:
        all_trials.extend(build_contrast_block(dimensions, contrast, story_1, story_2, evaluation_regime))

    print(
        f"{len(contrasts)} contrasts x 4 (assignment x position) = {len(all_trials)} prompts "
        f"({story_1['id']} = story_1, {story_2['id']} = story_2, evaluation_regime={evaluation_regime})\n"
    )

    for trial in all_trials:
        print(f"=== {trial['trial_id']} (assignment={trial['assignment']}, position={trial['position']}) ===")
        print(trial["prompt"])
        print()

    print("Summary: contrast_id | cell -> intro\n")
    for contrast in contrasts:
        print(f"{contrast['id']}")
        for cell in build_contrast_block(dimensions, contrast, story_1, story_2, evaluation_regime):
            print(f"  {cell['assignment']}/{cell['position']}: {cell['intro']}")
        print()


if __name__ == "__main__":
    main()
