"""Generate forward/flipped A-B trials from explicit context contrasts.

A contrast names two specific values of one dimension to pit against each other
(e.g. provenance "ai_claude" vs "human_unknown"), defined in
data/context_contrasts.jsonl -- not hardcoded here. story_1 is always Story A
and story_2 is always Story B, in both trials; only the contextual attribution
changes between them:

- a forward trial: story_1 (Story A) gets value "a", story_2 (Story B) gets value "b"
- a flipped trial: story_1 (Story A) gets value "b", story_2 (Story B) gets value "a"

Both stories always carry some context (never nothing) in both trials -- the
control comes from swapping which value each story gets, not from comparing
against an empty baseline. Since story identity and A/B position never move,
if the model's choice is really about the underlying stories, the same A/B
position should keep winning across the forward/flipped pair. If the
preference instead changes when the contexts are swapped, that's evidence the
context is doing the work, not the prose.

The contextual attribution is woven into a single deterministic opening
sentence (each contrast supplies its own "a_clause"/"b_clause" wording, hand
-written, not generated by an LLM) rather than posted as a label above each
story block -- see context_comparisons.INSTRUCTION_TEMPLATE.

Reuses context_comparisons.build_prompt() and its INSTRUCTION_TEMPLATE for the
actual prompt text (the existing natural "help me choose" / A-B-tie JSON
format) rather than duplicating it. Does not modify prompts.py, comparisons.py,
make_trials.py, run_trial.py, run_batch.py, analyze.py, or data/trials.jsonl,
and makes no API calls.

Run this file directly to print every forward/flipped prompt pair in full,
plus a summary table of each contrast's intro sentences.
"""

import json

from context_packets import load_dimensions
from context_comparisons import build_prompt, load_items, load_story

CONTRASTS_FILE = "data/context_contrasts.jsonl"


def load_contrasts(path=CONTRASTS_FILE):
    """Read data/context_contrasts.jsonl into a list of contrast dicts."""
    contrasts = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                contrasts.append(json.loads(line))
    return contrasts


def assert_no_shared_identity_contradiction(dimensions, contrast):
    """Refuse contrasts that would make one claimed identity contradict itself.

    A two-story prompt has a single "I" speaking for both stories at once. Any
    dimension that depends_on another dimension (currently just writer_status,
    which depends on provenance) describes a property of *the person*, not of
    the individual story -- so it cannot validly take two different values
    across Story A and Story B in the same prompt, no matter what carrier is
    used: "I am a published author" for Story A and "this is my first time
    writing" for Story B contradict each other, since they're both said by the
    same "I" in the same breath.

    Dimensions like this are single-story only (see context_single_prompts.py,
    where each API call only ever claims one identity for one story).
    """
    dim = dimensions[contrast["dimension"]]
    if dim.get("depends_on"):
        raise ValueError(
            f"Contrast {contrast['id']!r} uses dimension {contrast['dimension']!r}, which "
            f"depends on {dim['depends_on']!r}. Dependent dimensions describe a claimed "
            f"identity shared by both stories in a two-story prompt, so they can't be "
            f"contrasted across Story A/B without contradicting themselves. Use "
            f"context_single_prompts.py for this dimension instead."
        )


def assert_values_are_registered(dimensions, contrast):
    """Sanity-check that a contrast's "a"/"b" values are real, registered dimension values.

    The intro sentence uses the contrast's own a_clause/b_clause wording, not
    context_dimensions.jsonl's phrasing -- this check exists purely to catch
    typos (an "a"/"b" that doesn't match anything in context_dimensions.jsonl),
    not to render text.
    """
    dim = dimensions[contrast["dimension"]]
    for value_id in (contrast["a"], contrast["b"]):
        if value_id not in dim["values"]:
            raise ValueError(
                f"Contrast {contrast['id']!r} references unknown value {value_id!r} "
                f"for dimension {contrast['dimension']!r}"
            )


def intro_sentence(first_clause, second_clause):
    """Build the deterministic opening sentence naming Story A's and Story B's attribution."""
    return (
        f"Hi! Can you give me some feedback on these two stories? "
        f"Story A {first_clause}, while Story B {second_clause}. "
        f"I'm trying to make up my mind."
    )


def build_contrast_trials(dimensions, contrast, story_1, story_2):
    """Build the forward and flipped trial for one contrast, across two different stories.

    story_1 is always Story A and story_2 is always Story B in both trials --
    only which clause ("a_clause" or "b_clause") is attributed to which story
    changes between forward and flipped.
    """
    if story_1["id"] == story_2["id"]:
        raise ValueError("build_contrast_trials requires two different stories, not the same story twice")

    assert_no_shared_identity_contradiction(dimensions, contrast)
    assert_values_are_registered(dimensions, contrast)

    text_1 = load_story(story_1["path"])
    text_2 = load_story(story_2["path"])
    pair_id = f"{story_1['id']}_vs_{story_2['id']}"
    a_clause, b_clause = contrast["a_clause"], contrast["b_clause"]

    forward_intro = intro_sentence(a_clause, b_clause)
    flipped_intro = intro_sentence(b_clause, a_clause)

    forward = {
        "trial_id": f"contrast__{contrast['id']}__{pair_id}__forward",
        "contrast_id": contrast["id"],
        "dimension": contrast["dimension"],
        "story_a_id": story_1["id"],
        "story_b_id": story_2["id"],
        "intro": forward_intro,
        "prompt": build_prompt(forward_intro, text_1, text_2),
    }
    flipped = {
        "trial_id": f"contrast__{contrast['id']}__{pair_id}__flipped",
        "contrast_id": contrast["id"],
        "dimension": contrast["dimension"],
        "story_a_id": story_1["id"],
        "story_b_id": story_2["id"],
        "intro": flipped_intro,
        "prompt": build_prompt(flipped_intro, text_1, text_2),
    }
    return forward, flipped


def main():
    dimensions = load_dimensions()
    contrasts = load_contrasts()
    items = load_items()
    story_1, story_2 = items[0], items[1]  # a fixed, distinct pair keeps the example small

    all_trials = []
    for contrast in contrasts:
        forward, flipped = build_contrast_trials(dimensions, contrast, story_1, story_2)
        all_trials.append(forward)
        all_trials.append(flipped)

    print(
        f"{len(contrasts)} contrasts x 2 (forward/flipped) = {len(all_trials)} prompts "
        f"({story_1['id']} = Story A, {story_2['id']} = Story B, always)\n"
    )

    for trial in all_trials:
        print(f"=== {trial['trial_id']} ===")
        print(trial["prompt"])
        print()

    print("Summary: contrast_id | forward intro | flipped intro\n")
    for contrast in contrasts:
        forward_intro = intro_sentence(contrast["a_clause"], contrast["b_clause"])
        flipped_intro = intro_sentence(contrast["b_clause"], contrast["a_clause"])
        print(f"{contrast['id']}")
        print(f"  forward: {forward_intro}")
        print(f"  flipped: {flipped_intro}")
        print()


if __name__ == "__main__":
    main()
