"""The natural, non-experiment-flavored comparison prompt for context-packet trials.

This is a distinct prompt format from comparisons.py's numeric-rating format: it
frames the request as a casual ask for help choosing between two stories, and asks
for a plain A / B / tie choice per category instead of 1-5 ratings. It is
intentionally kept separate from prompts.py, comparisons.py, make_trials.py,
run_trial.py, run_batch.py, and analyze.py -- none of those are touched by this
file, and data/trials.jsonl is never written to, so the existing pipeline and its
results/raw.jsonl schema are unaffected.

This module just holds the prompt template and the shared load_items/load_story
helpers. The actual trial generator lives in context_contrasts.py, which reuses
build_prompt() from here, supplying an "intro" sentence that already has the
contextual attribution woven into it in plain English (e.g. "Story A was
generated by Claude, while Story B was written by someone whose identity I
don't know.") rather than posting the raw context as a separate label above
each story block.
"""

import json

ITEMS_FILE = "data/items.jsonl"

INSTRUCTION_TEMPLATE = """{intro}

Story A:
{story_a}

Story B:
{story_b}

For each category, choose which story is better.

Categories:
- Plot structure
- Prose style
- Characterisation
- Originality
- Overall quality

Return only JSON:

{{
  "plot_structure": "A",
  "prose_style": "B",
  "characterisation": "A",
  "originality": "tie",
  "overall_quality": "B"
}}"""


def load_items(path=ITEMS_FILE):
    """Read a .jsonl file and return a list of dicts (one per line)."""
    items = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                items.append(json.loads(line))
    return items


def load_story(path):
    """Read the story text from its .txt file."""
    with open(path, "r") as f:
        return f.read().strip()


def build_prompt(intro, story_a, story_b):
    """Fill in the natural comparison template with an intro sentence and two stories.

    intro is a complete, deterministic sentence (or two) that names the
    contextual attribution for both stories in plain English -- the caller
    (context_contrasts.py) is responsible for its exact wording.
    """
    return INSTRUCTION_TEMPLATE.format(intro=intro, story_a=story_a, story_b=story_b)
