"""Tests for the standalone context-controllability experiment's manifest
generator (controllability_trials.py).

Integration-level, like test_manifest_generation.py / test_llm_provenance_trials.py:
reads the real data/context_dimensions.jsonl, data/items.jsonl, and
data/controllability_contrasts.jsonl. No file under data/ is written by
these tests -- main() is only ever exercised with the output paths
monkeypatched to a tmp_path.
"""

import copy
import hashlib
import json

import pytest

import controllability_trials as ct
import run_batch as rb
from context_packets import load_dimensions
from context_trials import load_items, story_pairs
from run_trial import parse_and_validate


@pytest.fixture(scope="module")
def dims():
    return load_dimensions()


@pytest.fixture(scope="module")
def items():
    return load_items()


@pytest.fixture(scope="module")
def contrasts():
    return ct.load_contrasts(ct.CONTRASTS_FILE)


# ---------------------------------------------------------------------------
# 1. Frozen contrast wordings (spec item 11) -- deterministic, never
#    generated/paraphrased.
# ---------------------------------------------------------------------------

FROZEN_CLAUSES = {
    "provenance_human_vs_llm": ("was written by a human, but I don't know who", "was generated by an LLM"),
    "source_journal_vs_random": ("is something I found in a literary journal", "is something I stumbled across somewhere random online"),
    "reception_positive_vs_negative": ("has been very well received by the people who've read it", "has been very poorly received by the people who've read it"),
    "opinion_liked_vs_disliked": ("is one I really liked", "is one I really didn't like"),
    "editing_edited_vs_first_draft": ("has already been carefully edited", "is an unrevised first draft"),
}


def test_contrasts_file_has_exactly_the_five_required_contrasts(contrasts):
    assert {c["id"] for c in contrasts} == ct.REQUIRED_CONTRAST_IDS
    assert len(contrasts) == 5


@pytest.mark.parametrize("contrast_id,expected_clauses", FROZEN_CLAUSES.items())
def test_contrast_clauses_match_the_frozen_wording_exactly(contrasts, contrast_id, expected_clauses):
    contrast = next(c for c in contrasts if c["id"] == contrast_id)
    assert (contrast["a_clause"], contrast["b_clause"]) == expected_clauses


def test_each_contrast_isolates_a_distinct_dimension(contrasts):
    dimensions_used = [c["dimension"] for c in contrasts]
    assert len(dimensions_used) == len(set(dimensions_used))
    assert set(dimensions_used) == {"provenance", "source_venue", "reception", "user_opinion", "editing_status"}


def test_contrasts_use_registered_dimension_values(dims, contrasts):
    for c in contrasts:
        values = dims[c["dimension"]]["values"]
        assert c["a"] in values
        assert c["b"] in values


def test_every_contrast_has_a_display_name():
    for contrast_id in ct.REQUIRED_CONTRAST_IDS:
        assert contrast_id in ct.CONTRAST_DISPLAY_NAMES


# ---------------------------------------------------------------------------
# 2. assert_contrasts_are_well_formed: fail loudly on malformed input
# ---------------------------------------------------------------------------

def test_assert_contrasts_are_well_formed_accepts_the_real_file(dims, contrasts):
    ct.assert_contrasts_are_well_formed(dims, contrasts)  # must not raise


def test_rejects_duplicate_contrast_id(dims, contrasts):
    broken = contrasts + [dict(contrasts[0])]
    with pytest.raises(ValueError, match="Duplicate contrast id"):
        ct.assert_contrasts_are_well_formed(dims, broken)


def test_rejects_two_contrasts_sharing_a_dimension(dims, contrasts):
    duplicate_dimension = copy.deepcopy(contrasts[0])
    duplicate_dimension["id"] = "some_other_id"
    broken = contrasts + [duplicate_dimension]
    with pytest.raises(ValueError, match="already used by another contrast"):
        ct.assert_contrasts_are_well_formed(dims, broken)


def test_rejects_unregistered_dimension(dims, contrasts):
    broken = copy.deepcopy(contrasts)
    broken[0]["dimension"] = "not_a_real_dimension"
    with pytest.raises(ValueError, match="unregistered dimension"):
        ct.assert_contrasts_are_well_formed(dims, broken)


def test_rejects_unregistered_value(dims, contrasts):
    broken = copy.deepcopy(contrasts)
    broken[0]["b"] = "not_a_real_value"
    with pytest.raises(ValueError, match="unregistered value"):
        ct.assert_contrasts_are_well_formed(dims, broken)


def test_rejects_missing_or_substituted_contrast_ids(dims, contrasts):
    with pytest.raises(ValueError, match="Expected exactly the 5 contrasts"):
        ct.assert_contrasts_are_well_formed(dims, contrasts[:4])


# ---------------------------------------------------------------------------
# 3. Prompt wording: plain A/B, "Passage" (never "Story"), no JSON, single
#    outcome, and the exact naturalistic-vs-suppression difference.
# ---------------------------------------------------------------------------

def _one_block(contrasts, items, regime="naturalistic"):
    story_1, story_2 = story_pairs(items[:2])[0]
    return ct.build_treatment_block(contrasts[0], story_1, story_2, regime)


def test_prompts_use_passage_never_story(contrasts, items):
    cells = _one_block(contrasts, items)
    for c in cells:
        assert "Passage A" in c["prompt"]
        assert "Passage B" in c["prompt"]
        assert "Story A" not in c["prompt"]
        assert "Story B" not in c["prompt"]


def test_prompts_ask_a_single_plain_ab_question_no_json(contrasts, items):
    cells = _one_block(contrasts, items)
    for c in cells:
        assert "Please answer A or B" in c["prompt"]
        assert "Return only JSON" not in c["prompt"]
        assert '"overall_quality"' not in c["prompt"]
        assert "plot_structure" not in c["prompt"]
        assert "Categories:" not in c["prompt"]


def test_naturalistic_and_suppression_prompts_differ_only_by_the_instruction(contrasts, items):
    naturalistic_cells = _one_block(contrasts, items, "naturalistic")
    suppression_cells = _one_block(contrasts, items, "text_only_invariance")
    by_key_nat = {(c["assignment"], c["position"]): c for c in naturalistic_cells}
    by_key_sup = {(c["assignment"], c["position"]): c for c in suppression_cells}

    for key in by_key_nat:
        nat, sup = by_key_nat[key], by_key_sup[key]
        assert nat["intro"] == sup["intro"]
        assert nat["context_a"] == sup["context_a"]
        assert nat["context_b"] == sup["context_b"]
        expected_sup_prompt = nat["prompt"].replace(
            f"{nat['intro']}\n\n", f"{nat['intro']}\n\n{ct.SUPPRESSION_INSTRUCTION}\n\n", 1
        )
        assert sup["prompt"] == expected_sup_prompt


def test_suppression_instruction_is_exactly_the_frozen_sentence(contrasts, items):
    assert ct.SUPPRESSION_INSTRUCTION == (
        "For this comparison, I'm only interested in the writing itself. "
        "Please base your judgment on the passages as written."
    )
    cells = _one_block(contrasts, items, "text_only_invariance")
    for c in cells:
        assert ct.SUPPRESSION_INSTRUCTION in c["prompt"]


def test_suppression_prompt_never_enumerates_the_treatment_family_list(contrasts, items):
    """The old wording used to explicitly enumerate authorship/source/
    reception/editing/opinion, and used the words context/bias/invariance/
    suppression/irrelevant -- none of that may appear in the prompt."""
    cells = _one_block(contrasts, items, "text_only_invariance")
    banned_terms = [
        "authorship", "source", "reception", "editing status", "asker's own opinion",
        "irrelevant", "context", "bias", "invariance", "suppress",
    ]
    for c in cells:
        lowered = c["prompt"].lower()
        for term in banned_terms:
            assert term not in lowered, f"{term!r} must not appear in the suppression prompt"


def test_baseline_prompt_has_no_contextual_claim():
    items_local = load_items()
    baseline_trials = ct.build_baseline_trials(items_local[:2])
    for t in baseline_trials:
        assert "Passage A" in t["prompt"] and "Passage B" in t["prompt"]
        assert t["prompt"].startswith(ct.BASELINE_INTRO)
        # None of the 5 contrasts' clauses can have leaked in.
        for a_clause, b_clause in FROZEN_CLAUSES.values():
            assert a_clause not in t["prompt"]
            assert b_clause not in t["prompt"]


# ---------------------------------------------------------------------------
# 4. prompt_sha256: deterministic, matches the prompt, changes if the
#    prompt changes.
# ---------------------------------------------------------------------------

def test_prompt_sha256_matches_the_prompt(contrasts, items):
    cells = _one_block(contrasts, items)
    for c in cells:
        assert c["prompt_sha256"] == hashlib.sha256(c["prompt"].encode("utf-8")).hexdigest()


def test_prompt_sha256_differs_between_naturalistic_and_suppression(contrasts, items):
    naturalistic_cells = _one_block(contrasts, items, "naturalistic")
    suppression_cells = _one_block(contrasts, items, "text_only_invariance")
    nat_hashes = {c["prompt_sha256"] for c in naturalistic_cells}
    sup_hashes = {c["prompt_sha256"] for c in suppression_cells}
    assert nat_hashes.isdisjoint(sup_hashes)


def test_baseline_trials_carry_a_matching_prompt_sha256():
    items_local = load_items()
    baseline_trials = ct.build_baseline_trials(items_local[:2])
    for t in baseline_trials:
        assert t["prompt_sha256"] == hashlib.sha256(t["prompt"].encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# 5. assert_trials_are_well_formed / assert_baseline_trials_are_well_formed
# ---------------------------------------------------------------------------

def _one_real_block(contrasts, items):
    story_1, story_2 = story_pairs(items[:2])[0]
    trials = ct.build_treatment_block(contrasts[0], story_1, story_2, "naturalistic")
    for t in trials:
        t["experiment_id"] = ct.EXPERIMENT_ID
    assert len(trials) == 4
    return trials


def test_assert_trials_are_well_formed_accepts_one_real_block(contrasts, items):
    trials = _one_real_block(contrasts, items)
    by_block = ct.assert_trials_are_well_formed(trials)
    assert len(by_block) == 1
    assert len(list(by_block.values())[0]) == 4


def test_rejects_duplicate_trial_id(contrasts, items):
    trials = _one_real_block(contrasts, items)
    trials.append(dict(trials[0]))
    with pytest.raises(ValueError, match="Duplicate trial_id"):
        ct.assert_trials_are_well_formed(trials)


def test_rejects_wrong_type(contrasts, items):
    trials = _one_real_block(contrasts, items)
    trials[0] = {**trials[0], "type": "context_single"}
    with pytest.raises(ValueError, match="expected type 'context_pairwise'"):
        ct.assert_trials_are_well_formed(trials)


def test_rejects_wrong_choice_mode(contrasts, items):
    trials = _one_real_block(contrasts, items)
    trials[0] = {**trials[0], "choice_mode": "tie_allowed"}
    with pytest.raises(ValueError, match="expected choice_mode 'forced'"):
        ct.assert_trials_are_well_formed(trials)


def test_rejects_wrong_response_format(contrasts, items):
    trials = _one_real_block(contrasts, items)
    trials[0] = {**trials[0], "response_format": "structured"}
    with pytest.raises(ValueError, match="expected response_format 'plain_ab'"):
        ct.assert_trials_are_well_formed(trials)


def test_rejects_prompt_sha256_mismatch(contrasts, items):
    trials = _one_real_block(contrasts, items)
    trials[0] = {**trials[0], "prompt_sha256": "0" * 64}
    with pytest.raises(ValueError, match="prompt_sha256 does not match"):
        ct.assert_trials_are_well_formed(trials)


def test_rejects_unexpected_contrast_id(contrasts, items):
    trials = _one_real_block(contrasts, items)
    trials[0] = {**trials[0], "contrast_id": "provenance_claude_vs_human"}
    with pytest.raises(ValueError, match="unexpected contrast_id"):
        ct.assert_trials_are_well_formed(trials)


def test_rejects_block_with_fewer_than_four_cells(contrasts, items):
    trials = _one_real_block(contrasts, items)[:3]
    with pytest.raises(ValueError, match="expected exactly 4"):
        ct.assert_trials_are_well_formed(trials)


def test_rejects_block_missing_a_required_cell(contrasts, items):
    trials = _one_real_block(contrasts, items)
    trials[3] = {**trials[3], "assignment": trials[0]["assignment"], "position": trials[0]["position"],
                 "trial_id": trials[3]["trial_id"] + "_dup"}
    with pytest.raises(ValueError, match="expected \\["):
        ct.assert_trials_are_well_formed(trials)


def test_assert_baseline_trials_are_well_formed_accepts_real_baseline(items):
    baseline_trials = ct.build_baseline_trials(items[:2])
    by_block = ct.assert_baseline_trials_are_well_formed(baseline_trials)
    assert len(by_block) == 1
    assert len(list(by_block.values())[0]) == 2


def test_rejects_baseline_trial_carrying_an_assignment(items):
    baseline_trials = ct.build_baseline_trials(items[:2])
    baseline_trials[0] = {**baseline_trials[0], "assignment": "forward"}
    with pytest.raises(ValueError, match="must not carry a context 'assignment'"):
        ct.assert_baseline_trials_are_well_formed(baseline_trials)


def test_rejects_baseline_trial_under_the_wrong_regime(items):
    baseline_trials = ct.build_baseline_trials(items[:2])
    baseline_trials[0] = {**baseline_trials[0], "evaluation_regime": "text_only_invariance"}
    with pytest.raises(ValueError, match="naturalistic-only"):
        ct.assert_baseline_trials_are_well_formed(baseline_trials)


# ---------------------------------------------------------------------------
# 6. Manifest sizes: calculated, not hardcoded -- pinned to the spec's own
#    documented expectation too.
# ---------------------------------------------------------------------------

def test_treatment_manifest_matches_spec_expected_counts(dims, items, contrasts):
    from context_trials import EVALUATION_REGIMES

    n_pairs = len(items) * (len(items) - 1) // 2
    all_trials = []
    for regime in EVALUATION_REGIMES:
        for story_1, story_2 in story_pairs(items):
            for contrast in contrasts:
                for cell in ct.build_treatment_block(contrast, story_1, story_2, regime):
                    cell["experiment_id"] = ct.EXPERIMENT_ID
                    all_trials.append(cell)

    n_blocks = n_pairs * len(contrasts) * len(EVALUATION_REGIMES)
    assert (n_pairs, n_blocks, len(all_trials)) == (66, 660, 2640)  # spec's documented expectation
    by_block = ct.assert_trials_are_well_formed(all_trials)
    assert len(by_block) == n_blocks


def test_baseline_manifest_matches_spec_expected_counts(items):
    baseline_trials = ct.build_baseline_trials(items)
    n_pairs = len(items) * (len(items) - 1) // 2
    assert (n_pairs, len(baseline_trials)) == (66, 132)  # spec's documented expectation
    by_block = ct.assert_baseline_trials_are_well_formed(baseline_trials)
    assert len(by_block) == n_pairs


# ---------------------------------------------------------------------------
# 7. main(): end-to-end, output redirected to tmp_path
# ---------------------------------------------------------------------------

def test_main_writes_2640_treatment_and_132_baseline_trials(tmp_path, monkeypatch):
    treatment_path = tmp_path / "controllability_trials.jsonl"
    baseline_path = tmp_path / "controllability_baseline_trials.jsonl"
    monkeypatch.setattr(ct, "TRIALS_FILE", str(treatment_path))
    monkeypatch.setattr(ct, "BASELINE_TRIALS_FILE", str(baseline_path))

    ct.main()

    treatment_lines = treatment_path.read_text(encoding="utf-8").splitlines()
    baseline_lines = baseline_path.read_text(encoding="utf-8").splitlines()
    assert len(treatment_lines) == 2640
    assert len(baseline_lines) == 132

    treatment_trials = [json.loads(line) for line in treatment_lines]
    assert all(t["experiment_id"] == ct.EXPERIMENT_ID for t in treatment_trials)
    assert all(t["response_format"] == "plain_ab" for t in treatment_trials)
    assert all(t["type"] == "context_pairwise" and t["choice_mode"] == "forced" for t in treatment_trials)
    assert all("prompt_sha256" in t and t["prompt_sha256"] for t in treatment_trials)
    assert len({t["prompt_sha256"] for t in treatment_trials}) == 2640  # every prompt is unique

    baseline_trials = [json.loads(line) for line in baseline_lines]
    assert all(t["experiment_id"] == ct.BASELINE_EXPERIMENT_ID for t in baseline_trials)
    assert all("assignment" not in t for t in baseline_trials)
    assert all(t["evaluation_regime"] == "naturalistic" for t in baseline_trials)
    assert all("prompt_sha256" in t and t["prompt_sha256"] for t in baseline_trials)


def test_broad_general_benchmark_is_unaffected_by_this_experiment(dims, items):
    """The general benchmark's own trial builder is untouched -- it never
    imports controllability_trials.py, and this experiment no longer calls
    context_contrasts.build_contrast_block()/context_trials.
    build_context_pairwise_trials() at all."""
    from context_contrasts import load_contrasts as load_general_contrasts
    from context_trials import build_context_pairwise_trials

    general = build_context_pairwise_trials(dims, items[:2], "naturalistic")
    assert len(general) == len(load_general_contrasts()) * 4
    assert all(t["rubric"] == "full" for t in general)
    assert all("experiment_id" not in t for t in general)
    assert all("prompt_sha256" not in t for t in general)
    assert all("response_format" not in t for t in general)


# ---------------------------------------------------------------------------
# 8. Runner integration: reuse run_batch.py unmodified.
# ---------------------------------------------------------------------------

def test_run_batch_limit_1_selects_exactly_one_complete_treatment_block(dims, items, contrasts):
    from context_trials import EVALUATION_REGIMES

    all_trials = []
    for story_1, story_2 in story_pairs(items):
        for contrast in contrasts:
            for cell in ct.build_treatment_block(contrast, story_1, story_2, "naturalistic"):
                cell["experiment_id"] = ct.EXPERIMENT_ID
                all_trials.append(cell)

    selected = rb.select_trials(all_trials, None, None, None, None, None, limit=1)
    assert len(selected) == 4
    assert len({t["block_id"] for t in selected}) == 1


def test_run_batch_limit_2_selects_exactly_two_complete_treatment_blocks(items, contrasts):
    all_trials = []
    for story_1, story_2 in story_pairs(items):
        for contrast in contrasts:
            for cell in ct.build_treatment_block(contrast, story_1, story_2, "naturalistic"):
                cell["experiment_id"] = ct.EXPERIMENT_ID
                all_trials.append(cell)

    selected = rb.select_trials(all_trials, None, None, None, None, None, limit=2)
    assert len(selected) == 8
    block_ids = {t["block_id"] for t in selected}
    assert len(block_ids) == 2
    for bid in block_ids:
        assert len([t for t in selected if t["block_id"] == bid]) == 4


def test_run_batch_treats_baseline_pairs_as_two_cell_units(items):
    baseline_trials = ct.build_baseline_trials(items)
    selected = rb.select_trials(baseline_trials, None, None, None, None, None, limit=1)
    assert len(selected) == 2
    assert len({t["block_id"] for t in selected}) == 1


def test_treatment_trials_pass_existing_forced_choice_validation_via_response_format(contrasts, items):
    trials = _one_real_block(contrasts, items)
    for t in trials:
        parsed, error = parse_and_validate("A", t["type"], t.get("choice_mode"), t.get("rubric", "full"), t.get("response_format"))
        assert error is None
        assert parsed == {"overall_quality": "A"}


def test_baseline_trials_pass_existing_forced_choice_validation_via_response_format(items):
    baseline_trials = ct.build_baseline_trials(items[:2])
    for t in baseline_trials:
        parsed, error = parse_and_validate("B", t["type"], t.get("choice_mode"), t.get("rubric", "full"), t.get("response_format"))
        assert error is None
        assert parsed == {"overall_quality": "B"}


# ---------------------------------------------------------------------------
# 9. Completion/resume identity: run_batch.is_completed must respect
#    prompt_sha256 (item 3 of the "cleanup" list).
# ---------------------------------------------------------------------------

def test_is_completed_ignores_a_result_saved_against_a_different_prompt_hash():
    records = [{"parsed_response": {"overall_quality": "A"}, "validation_error": None,
                "trial_meta": {"prompt_sha256": "old_hash"}}]
    assert rb.is_completed(records, expected_prompt_sha256="old_hash") is True
    assert rb.is_completed(records, expected_prompt_sha256="new_hash") is False


def test_is_completed_is_unaffected_for_trials_without_a_prompt_sha256():
    """Every trial type except this experiment has no prompt_sha256 at all
    -- passing None must reproduce the exact old behavior."""
    records = [{"parsed_response": {"x": 1}, "validation_error": None}]
    assert rb.is_completed(records) is True
    assert rb.is_completed(records, expected_prompt_sha256=None) is True
