"""Tests for the standalone named-LLM provenance pairwise experiment's
manifest generator (llm_provenance_trials.py).

Integration-level, like test_manifest_generation.py: reads the real
data/context_dimensions.jsonl, data/items.jsonl, and
data/llm_provenance_contrasts.jsonl rather than synthetic fixtures, since
the whole point of this module is to fail loudly if THOSE real files ever
drift out of the shape this experiment requires. No file under data/ is
written by these tests -- main() is only ever exercised with TRIALS_FILE
monkeypatched to a tmp_path.
"""

import copy
import itertools
import json

import pytest

import run_batch as rb
from context_packets import load_dimensions
from context_trials import EVALUATION_REGIMES, build_context_pairwise_trials, load_items
from run_trial import parse_and_validate
import llm_provenance_trials as lpt


@pytest.fixture(scope="module")
def dims():
    return load_dimensions()


@pytest.fixture(scope="module")
def items():
    return load_items()


@pytest.fixture(scope="module")
def contrasts():
    return lpt.load_contrasts(lpt.CONTRASTS_FILE)


# ---------------------------------------------------------------------------
# 1. The dedicated contrast file itself
# ---------------------------------------------------------------------------

def test_contrasts_file_has_exactly_six_rows(contrasts):
    assert len(contrasts) == 6 == len(lpt.PROVENANCE_LABELS) * (len(lpt.PROVENANCE_LABELS) - 1) // 2


def test_contrasts_are_exactly_all_c4_2_unordered_pairs(contrasts):
    expected_pairs = {frozenset(pair) for pair in itertools.combinations(lpt.PROVENANCE_LABELS, 2)}
    actual_pairs = {frozenset((c["a"], c["b"])) for c in contrasts}
    assert actual_pairs == expected_pairs


def test_contrasts_use_the_provenance_dimension_and_registered_values(dims, contrasts):
    for c in contrasts:
        assert c["dimension"] == "provenance"
        assert c["a"] in dims["provenance"]["values"]
        assert c["b"] in dims["provenance"]["values"]


def test_contrasts_do_not_repurpose_the_pre_existing_edited_value(contrasts):
    used_values = {v for c in contrasts for v in (c["a"], c["b"])}
    assert "ai_gemini_edited" not in used_values


def test_general_context_dimensions_still_has_all_pre_existing_provenance_values(dims):
    """Adding ai_gemini/ai_deepseek must be additive -- every pre-existing
    provenance value stays registered with its original wording untouched."""
    values = dims["provenance"]["values"]
    assert values["ai_claude"] == "This was generated by Claude."
    assert values["ai_chatgpt"] == "This was generated by ChatGPT."
    assert values["ai_gemini"] == "This was generated by Gemini."
    assert values["ai_deepseek"] == "This was generated by DeepSeek."
    assert "ai_gemini_edited" in values  # untouched, not repurposed


# ---------------------------------------------------------------------------
# 2. assert_contrasts_are_well_formed: fail loudly on every malformed input
# ---------------------------------------------------------------------------

def test_assert_contrasts_are_well_formed_accepts_the_real_file(dims, contrasts):
    lpt.assert_contrasts_are_well_formed(dims, contrasts)  # must not raise


def test_rejects_duplicate_contrast_id(dims, contrasts):
    broken = contrasts + [dict(contrasts[0])]
    with pytest.raises(ValueError, match="Duplicate contrast id"):
        lpt.assert_contrasts_are_well_formed(dims, broken)


def test_rejects_duplicate_unordered_pairing(dims, contrasts):
    dup = dict(contrasts[0])
    dup["id"] = "some_other_id"
    broken = contrasts + [dup]
    with pytest.raises(ValueError, match="Duplicate unordered pairing"):
        lpt.assert_contrasts_are_well_formed(dims, broken)


def test_rejects_unregistered_provenance_value(dims, contrasts):
    broken = copy.deepcopy(contrasts)
    broken[0]["b"] = "ai_not_a_real_model"
    with pytest.raises(ValueError, match="unregistered provenance value"):
        lpt.assert_contrasts_are_well_formed(dims, broken)


def test_rejects_a_value_outside_the_four_experimental_labels(dims, contrasts):
    """human_unknown is a real, registered provenance value (used by the
    general benchmark) but is not one of the four named-LLM labels this
    focused experiment manipulates."""
    broken = copy.deepcopy(contrasts)
    broken[0]["b"] = "human_unknown"
    with pytest.raises(ValueError, match="not one of the four"):
        lpt.assert_contrasts_are_well_formed(dims, broken)


def test_rejects_wrong_dimension(dims, contrasts):
    broken = copy.deepcopy(contrasts)
    broken[0]["dimension"] = "writer_status"
    with pytest.raises(ValueError, match="expected dimension 'provenance'"):
        lpt.assert_contrasts_are_well_formed(dims, broken)


def test_rejects_wrong_total_count(dims, contrasts):
    with pytest.raises(ValueError, match="Expected exactly 6 contrasts"):
        lpt.assert_contrasts_are_well_formed(dims, contrasts[:5])


# ---------------------------------------------------------------------------
# 3. assert_trials_are_well_formed: fail loudly on every malformed manifest
# ---------------------------------------------------------------------------

def _one_real_block(dims, items, contrasts):
    trials = build_context_pairwise_trials(dims, items[:2], "naturalistic", choice_mode="forced", contrasts=contrasts[:1])
    assert len(trials) == 4
    return trials


def test_assert_trials_are_well_formed_accepts_one_real_block(dims, items, contrasts):
    trials = _one_real_block(dims, items, contrasts)
    by_block = lpt.assert_trials_are_well_formed(trials)
    assert len(by_block) == 1
    assert len(list(by_block.values())[0]) == 4


def test_rejects_duplicate_trial_id(dims, items, contrasts):
    trials = _one_real_block(dims, items, contrasts)
    trials.append(dict(trials[0]))
    with pytest.raises(ValueError, match="Duplicate trial_id"):
        lpt.assert_trials_are_well_formed(trials)


def test_rejects_wrong_type(dims, items, contrasts):
    trials = _one_real_block(dims, items, contrasts)
    trials[0] = {**trials[0], "type": "context_single"}
    with pytest.raises(ValueError, match="expected type 'context_pairwise'"):
        lpt.assert_trials_are_well_formed(trials)


def test_rejects_wrong_choice_mode(dims, items, contrasts):
    trials = _one_real_block(dims, items, contrasts)
    trials[0] = {**trials[0], "choice_mode": "tie_allowed"}
    with pytest.raises(ValueError, match="expected choice_mode 'forced'"):
        lpt.assert_trials_are_well_formed(trials)


def test_rejects_block_with_fewer_than_four_cells(dims, items, contrasts):
    trials = _one_real_block(dims, items, contrasts)[:3]
    with pytest.raises(ValueError, match="expected exactly 4"):
        lpt.assert_trials_are_well_formed(trials)


def test_rejects_block_with_a_duplicated_cell_instead_of_all_four_required(dims, items, contrasts):
    trials = _one_real_block(dims, items, contrasts)
    trials[3] = {**trials[3], "assignment": trials[0]["assignment"], "position": trials[0]["position"],
                 "trial_id": trials[3]["trial_id"] + "_dup"}
    with pytest.raises(ValueError, match="expected \\["):
        lpt.assert_trials_are_well_formed(trials)


# ---------------------------------------------------------------------------
# 4. Manifest sizes: calculated, not hardcoded -- but pinned to the spec's
#    documented expectation too, so a silent drift in item counts is caught.
# ---------------------------------------------------------------------------

def expected_block_and_trial_counts(items, contrasts, n_regimes):
    n_pairs = len(items) * (len(items) - 1) // 2
    n_blocks = n_pairs * len(contrasts) * n_regimes
    return n_blocks, n_blocks * 4


def test_naturalistic_only_manifest_matches_spec_expected_counts(dims, items, contrasts):
    trials = build_context_pairwise_trials(dims, items, "naturalistic", choice_mode="forced", contrasts=contrasts)
    n_blocks, n_trials = expected_block_and_trial_counts(items, contrasts, 1)
    assert (n_blocks, n_trials) == (396, 1584)  # spec item 8's documented expectation
    by_block = lpt.assert_trials_are_well_formed(trials)
    assert len(trials) == n_trials
    assert len(by_block) == n_blocks


def test_both_regimes_manifest_matches_spec_expected_counts(dims, items, contrasts):
    trials = []
    for regime in EVALUATION_REGIMES:
        trials += build_context_pairwise_trials(dims, items, regime, choice_mode="forced", contrasts=contrasts)
    n_blocks, n_trials = expected_block_and_trial_counts(items, contrasts, len(EVALUATION_REGIMES))
    assert (n_blocks, n_trials) == (792, 3168)  # spec item 8's documented expectation
    by_block = lpt.assert_trials_are_well_formed(trials)
    assert len(trials) == n_trials
    assert len(by_block) == n_blocks


def test_default_evaluation_regime_is_naturalistic_only():
    assert lpt.DEFAULT_EVALUATION_REGIMES == ["naturalistic"]


# ---------------------------------------------------------------------------
# 5. CLI: repeatable --evaluation-regime flag, matching run_batch.py's convention
# ---------------------------------------------------------------------------

def test_cli_defaults_to_none_so_main_falls_back_to_naturalistic_only():
    args = lpt.build_argument_parser().parse_args([])
    assert args.evaluation_regimes is None


def test_cli_evaluation_regime_flag_is_repeatable():
    args = lpt.build_argument_parser().parse_args(
        ["--evaluation-regime", "naturalistic", "--evaluation-regime", "text_only_invariance"]
    )
    assert args.evaluation_regimes == ["naturalistic", "text_only_invariance"]


def test_cli_rejects_an_unknown_evaluation_regime():
    with pytest.raises(SystemExit):
        lpt.build_argument_parser().parse_args(["--evaluation-regime", "not_a_real_regime"])


# ---------------------------------------------------------------------------
# 6. main(): end-to-end, output redirected to tmp_path -- never touches
#    data/llm_provenance_trials.jsonl.
# ---------------------------------------------------------------------------

def test_main_writes_expected_trial_count_and_tags_every_trial_with_experiment_id(tmp_path, monkeypatch, capsys):
    out_path = tmp_path / "llm_provenance_trials.jsonl"
    monkeypatch.setattr(lpt, "TRIALS_FILE", str(out_path))
    monkeypatch.setattr("sys.argv", ["llm_provenance_trials.py"])

    lpt.main()

    lines = out_path.read_text().splitlines()
    assert len(lines) == 1584
    trials = [json.loads(line) for line in lines]
    assert all(t["experiment_id"] == lpt.EXPERIMENT_ID for t in trials)
    assert all(t["type"] == "context_pairwise" and t["choice_mode"] == "forced" for t in trials)

    out = capsys.readouterr().out
    assert "Blocks: 396" in out
    assert "Trials: 1584" in out


def test_main_with_both_regimes_flag_writes_double_the_trials(tmp_path, monkeypatch):
    out_path = tmp_path / "llm_provenance_trials.jsonl"
    monkeypatch.setattr(lpt, "TRIALS_FILE", str(out_path))
    monkeypatch.setattr(
        "sys.argv",
        ["llm_provenance_trials.py", "--evaluation-regime", "naturalistic", "--evaluation-regime", "text_only_invariance"],
    )

    lpt.main()

    lines = out_path.read_text().splitlines()
    assert len(lines) == 3168


# ---------------------------------------------------------------------------
# 7. Manual-inspection checklist (spec item 20), automated for one block:
#    fixed prose, correct provenance-assignment swap, correct position swap,
#    fixed story identity, one shared block_id.
# ---------------------------------------------------------------------------

def test_one_block_satisfies_the_full_manual_inspection_checklist(dims, items, contrasts):
    trials = _one_real_block(dims, items, contrasts)
    by_cell = {(t["assignment"], t["position"]): t for t in trials}
    assert set(by_cell) == lpt.REQUIRED_CELLS

    # All four cells share one block_id.
    assert len({t["block_id"] for t in trials}) == 1

    # story_1_id/story_2_id are fixed across all four cells.
    assert len({t["story_1_id"] for t in trials}) == 1
    assert len({t["story_2_id"] for t in trials}) == 1
    story_1_id = trials[0]["story_1_id"]
    story_2_id = trials[0]["story_2_id"]
    assert story_1_id != story_2_id

    # story_a_id/story_b_id reflect DISPLAYED position, not context assignment.
    for (assignment, position), t in by_cell.items():
        if position == "story1_as_a":
            assert t["story_a_id"] == story_1_id and t["story_b_id"] == story_2_id
        else:
            assert t["story_a_id"] == story_2_id and t["story_b_id"] == story_1_id

    # Provenance assignment swaps correctly between forward/flipped, and
    # context_a/context_b track whichever story is displayed in that slot.
    contrast = contrasts[0]
    for (assignment, position), t in by_cell.items():
        story_1_value = contrast["a"] if assignment == "forward" else contrast["b"]
        story_2_value = contrast["b"] if assignment == "forward" else contrast["a"]
        expected_a_value = story_1_value if position == "story1_as_a" else story_2_value
        expected_b_value = story_2_value if position == "story1_as_a" else story_1_value
        assert t["context_a"]["value"] == expected_a_value
        assert t["context_b"]["value"] == expected_b_value

    # Prose is byte-identical across cells -- only the intro sentence's
    # claimed attribution (and which story sits in which display slot)
    # legitimately differs, never the story text itself. Holding position
    # fixed and varying only assignment (forward vs flipped) isolates that:
    # the displayed Story A/Story B blocks must be byte-identical, since
    # assignment only changes the intro's claimed attribution.
    def story_bodies(prompt):
        return prompt.split("I'm trying to make up my mind.", 1)[1]

    for position in ("story1_as_a", "story2_as_a"):
        bodies = {story_bodies(by_cell[(assignment, position)]["prompt"]) for assignment in ("forward", "flipped")}
        assert len(bodies) == 1, f"story prose at position={position} must be identical across forward/flipped"

    # And the same two underlying story bodies appear across all four
    # cells, regardless of which display slot they land in (varying
    # position, not just assignment).
    reference_bodies = {
        by_cell[("forward", "story1_as_a")]["prompt"].split("I'm trying to make up my mind.", 1)[1],
        by_cell[("forward", "story2_as_a")]["prompt"].split("I'm trying to make up my mind.", 1)[1],
    }
    for t in trials:
        assert story_bodies(t["prompt"]) in reference_bodies


# ---------------------------------------------------------------------------
# 8. Runner integration: reuse run_batch.py unmodified.
# ---------------------------------------------------------------------------

def test_run_batch_limit_2_selects_exactly_two_complete_four_cell_blocks(dims, items, contrasts):
    trials = build_context_pairwise_trials(dims, items, "naturalistic", choice_mode="forced", contrasts=contrasts)
    selected = rb.select_trials(trials, None, None, None, None, None, limit=2)
    assert len(selected) == 8
    block_ids = {t["block_id"] for t in selected}
    assert len(block_ids) == 2
    for bid in block_ids:
        assert len([t for t in selected if t["block_id"] == bid]) == 4


def test_run_batch_limit_1_selects_exactly_one_complete_block(dims, items, contrasts):
    trials = build_context_pairwise_trials(dims, items, "naturalistic", choice_mode="forced", contrasts=contrasts)
    selected = rb.select_trials(trials, None, None, None, None, None, limit=1)
    assert len(selected) == 4
    assert len({t["block_id"] for t in selected}) == 1


def test_dedicated_trials_pass_existing_forced_choice_validation_with_no_new_validator(dims, items, contrasts):
    """The dedicated manifest's trials must validate through the SAME
    validate_pairwise_context_response_forced path as the general benchmark
    -- no bespoke validator for this experiment."""
    trials = _one_real_block(dims, items, contrasts)
    well_formed_response = json.dumps(
        {"plot_structure": "A", "prose_style": "B", "characterization": "A", "originality": "B", "overall_quality": "A"}
    )
    for t in trials:
        parsed, error = parse_and_validate(well_formed_response, t["type"], t.get("choice_mode"))
        assert error is None
        assert parsed["overall_quality"] == "A"


# ---------------------------------------------------------------------------
# 9. Backwards compatibility: the shared refactor and new dimension values
#    change nothing about the broad benchmark's pairwise/prompt families.
# ---------------------------------------------------------------------------

def test_omitting_contrasts_still_uses_the_full_general_benchmark_set(dims, items):
    from context_contrasts import load_contrasts as load_general_contrasts

    general = build_context_pairwise_trials(dims, items[:2], "naturalistic")
    assert len(general) == len(load_general_contrasts()) * 4


def test_experiment_id_is_not_present_on_general_benchmark_trials(dims, items):
    general = build_context_pairwise_trials(dims, items[:2], "naturalistic")
    assert all("experiment_id" not in t for t in general)
