"""Tests for the standalone named-LLM provenance experiment's focused
analyser (analyze_llm_provenance.py).

Synthetic-fixture style, like tests/test_analyze_context.py's
TestDirectionalPairwiseEffect (make_full_block etc.) -- these tests build
observation dicts directly rather than running real trials/API calls, since
every effect-size calculation here is reused, unmodified, from
context_analysis_pairwise.py/context_analysis_io.py. What's under test is
this module's own thin composition: label attachment from structured
contrast fields, and the antisymmetric provenance matrix -- never a second
statistics implementation.
"""

import pytest

from context_analysis_common import RATING_FIELDS
from context_analysis_pairwise import (
    analyze_directional_pairwise_effects,
    analyze_pairwise_cell_rates,
    analyze_position_and_interaction_effects,
    summarize_directional_effects_by_contrast,
)

import analyze_llm_provenance as alp
import llm_provenance_trials as lpt


CLAUDE_VS_CHATGPT = {
    "id": "provenance_claude_vs_chatgpt", "dimension": "provenance",
    "a": "ai_claude", "b": "ai_chatgpt",
    "a_clause": "was generated by Claude", "b_clause": "was generated by ChatGPT",
    "hypothesis": "x",
}


def make_cell_obs(model, evaluation_regime, contrast_id, s1, s2, assignment, position, wins, n, prefix, choice_mode="forced"):
    """wins = number of replicates (out of n) where story_1 is the chosen story.
    Mirrors tests/test_analyze_context.py's helper of the same name exactly,
    since the underlying observation shape these functions read is unchanged
    by this focused experiment."""
    obs = {}
    for rep in range(1, n + 1):
        story_1_chosen = rep <= wins
        if position == "story1_as_a":
            story_a_id, story_b_id = s1, s2
            choice = "A" if story_1_chosen else "B"
        else:
            story_a_id, story_b_id = s2, s1
            choice = "B" if story_1_chosen else "A"
        obs[f"{prefix}_{rep}"] = {
            "type": "context_pairwise", "model": model, "evaluation_regime": evaluation_regime,
            "choice_mode": choice_mode, "contrast_id": contrast_id, "story_1_id": s1, "story_2_id": s2,
            "story_a_id": story_a_id, "story_b_id": story_b_id, "assignment": assignment, "position": position,
            "replicate_id": rep, "parsed_response": {f: choice for f in RATING_FIELDS},
            "experiment_id": lpt.EXPERIMENT_ID,
        }
    return obs


def make_full_block(model, evaluation_regime, contrast_id, s1, s2, fwd_a, fwd_b, flp_a, flp_b, n=10, prefix="x", choice_mode="forced"):
    obs = {}
    obs.update(make_cell_obs(model, evaluation_regime, contrast_id, s1, s2, "forward", "story1_as_a", fwd_a, n, f"{prefix}_fa", choice_mode))
    obs.update(make_cell_obs(model, evaluation_regime, contrast_id, s1, s2, "forward", "story2_as_a", fwd_b, n, f"{prefix}_fb", choice_mode))
    obs.update(make_cell_obs(model, evaluation_regime, contrast_id, s1, s2, "flipped", "story1_as_a", flp_a, n, f"{prefix}_pa", choice_mode))
    obs.update(make_cell_obs(model, evaluation_regime, contrast_id, s1, s2, "flipped", "story2_as_a", flp_b, n, f"{prefix}_pb", choice_mode))
    return obs


def pipeline(observations, contrasts=(CLAUDE_VS_CHATGPT,)):
    """Run exactly the same composition analyze_llm_provenance.main() runs,
    minus I/O, and return (by_contrast_rows, matrices, position_rows)."""
    labels_by_contrast_id = alp.contrast_labels(list(contrasts))
    directional_rows = alp.attach_labels(analyze_directional_pairwise_effects(observations), labels_by_contrast_id)
    by_contrast_rows = alp.attach_labels(summarize_directional_effects_by_contrast(directional_rows), labels_by_contrast_id)
    cell_rows = analyze_pairwise_cell_rates(observations)
    position_rows = alp.attach_labels(analyze_position_and_interaction_effects(cell_rows), labels_by_contrast_id)
    matrices = alp.build_provenance_matrix(by_contrast_rows)
    return directional_rows, by_contrast_rows, matrices, position_rows


# ---------------------------------------------------------------------------
# contrast_labels / attach_labels: from structured fields, never contrast_id text
# ---------------------------------------------------------------------------

def test_contrast_labels_come_from_structured_a_b_fields():
    labels = alp.contrast_labels([CLAUDE_VS_CHATGPT])
    assert labels["provenance_claude_vs_chatgpt"] == ("Claude", "ChatGPT")


def test_contrast_labels_covers_all_six_real_contrasts():
    contrasts = lpt.load_contrasts(lpt.CONTRASTS_FILE)
    labels = alp.contrast_labels(contrasts)
    assert len(labels) == 6
    assert set(labels["provenance_gemini_vs_deepseek"]) == {"Gemini", "DeepSeek"}


def test_attach_labels_adds_label_a_and_label_b_in_place():
    rows = [{"contrast_id": "provenance_claude_vs_chatgpt"}]
    alp.attach_labels(rows, alp.contrast_labels([CLAUDE_VS_CHATGPT]))
    assert rows[0]["label_a"] == "Claude"
    assert rows[0]["label_b"] == "ChatGPT"


# ---------------------------------------------------------------------------
# Fixture (a): Claude-attributed story always wins, balanced positions ->
# +1.0 directional effect; inverting the labels must flip the matrix sign.
# ---------------------------------------------------------------------------

class TestClaudeAlwaysWinsFixture:
    def test_directional_effect_is_plus_one(self):
        # forward: story_1 carries "a" (Claude) and always wins, both positions.
        # flipped: story_1 carries "b" (ChatGPT) and always loses, both positions.
        obs = make_full_block("m", "naturalistic", "provenance_claude_vs_chatgpt", "s1", "s2",
                               fwd_a=10, fwd_b=10, flp_a=0, flp_b=0)
        directional_rows, by_contrast_rows, matrices, _ = pipeline(obs)

        quality_row = next(r for r in by_contrast_rows if r["category"] == "overall_quality")
        assert quality_row["mean_directional_effect"] == pytest.approx(1.0)
        assert quality_row["label_a"] == "Claude"
        assert quality_row["label_b"] == "ChatGPT"

    def test_matrix_is_antisymmetric_and_matches_the_directional_effect(self):
        obs = make_full_block("m", "naturalistic", "provenance_claude_vs_chatgpt", "s1", "s2",
                               fwd_a=10, fwd_b=10, flp_a=0, flp_b=0)
        _, _, matrices, _ = pipeline(obs)
        matrix = matrices[("m", "naturalistic")]

        assert matrix["Claude"]["ChatGPT"] == pytest.approx(1.0)
        assert matrix["ChatGPT"]["Claude"] == pytest.approx(-1.0)
        assert matrix["Claude"]["Claude"] == 0.0
        assert matrix["ChatGPT"]["ChatGPT"] == 0.0

    def test_inverting_which_label_is_a_flips_the_matrix_sign(self):
        """Same underlying story preference (story_1 always wins when it
        carries whichever value is now labelled "a"), but with a/b swapped
        in the contrast definition itself -- the matrix must still be
        internally antisymmetric and the two runs must be exact mirrors."""
        inverted_contrast = {**CLAUDE_VS_CHATGPT, "a": "ai_chatgpt", "b": "ai_claude",
                              "a_clause": "was generated by ChatGPT", "b_clause": "was generated by Claude"}

        obs = make_full_block("m", "naturalistic", "provenance_claude_vs_chatgpt", "s1", "s2",
                               fwd_a=10, fwd_b=10, flp_a=0, flp_b=0)
        _, _, original_matrices, _ = pipeline(obs, contrasts=(CLAUDE_VS_CHATGPT,))
        _, _, inverted_matrices, _ = pipeline(obs, contrasts=(inverted_contrast,))

        original = original_matrices[("m", "naturalistic")]
        inverted = inverted_matrices[("m", "naturalistic")]
        assert original["Claude"]["ChatGPT"] == pytest.approx(-inverted["Claude"]["ChatGPT"])
        assert inverted["Claude"]["ChatGPT"] == pytest.approx(-1.0)
        assert inverted["ChatGPT"]["Claude"] == pytest.approx(1.0)


# ---------------------------------------------------------------------------
# Fixture (b): story preference never changes when labels swap -> 0.0 effect
# ---------------------------------------------------------------------------

class TestLabelInvariantPreferenceFixture:
    def test_directional_effect_is_zero(self):
        # 50/50 in every cell, regardless of which story carries which label.
        obs = make_full_block("m", "naturalistic", "provenance_claude_vs_chatgpt", "s1", "s2",
                               fwd_a=5, fwd_b=5, flp_a=5, flp_b=5)
        directional_rows, by_contrast_rows, matrices, _ = pipeline(obs)

        quality_row = next(r for r in by_contrast_rows if r["category"] == "overall_quality")
        assert quality_row["mean_directional_effect"] == pytest.approx(0.0)

        matrix = matrices[("m", "naturalistic")]
        assert matrix["Claude"]["ChatGPT"] == pytest.approx(0.0)
        assert matrix["ChatGPT"]["Claude"] == pytest.approx(0.0)


# ---------------------------------------------------------------------------
# Fixture (c): position-biased fixture -- the position analysis must
# identify the position effect separately from (and here, larger than) the
# pooled provenance effect.
# ---------------------------------------------------------------------------

class TestPositionBiasIsSeparatedFromProvenanceEffect:
    def test_position_effect_is_reported_and_distinct_from_the_pooled_provenance_effect(self):
        # forward: story1_as_a=8/10, story1_as_b=4/10; flipped: 6/10, 2/10
        # (identical to test_analyze_context.py's own position-confound
        # fixture -- same underlying phenomenon, now read through this
        # module's label-attaching composition instead of directly).
        obs = make_full_block("m", "naturalistic", "provenance_claude_vs_chatgpt", "s1", "s2",
                               fwd_a=8, fwd_b=4, flp_a=6, flp_b=2)
        directional_rows, by_contrast_rows, matrices, position_rows = pipeline(obs)

        quality_row = next(r for r in by_contrast_rows if r["category"] == "overall_quality")
        assert quality_row["mean_directional_effect"] == pytest.approx(0.2)

        position_row = next(r for r in position_rows if r["category"] == "overall_quality")
        assert position_row["label_a"] == "Claude"
        assert position_row["label_b"] == "ChatGPT"
        assert position_row["position_effect_pooled"] == pytest.approx(0.4)

        # The position effect is larger than -- and reported separately
        # from -- the pooled provenance-label effect that ends up in the matrix.
        assert abs(position_row["position_effect_pooled"]) > abs(quality_row["mean_directional_effect"])

        matrix = matrices[("m", "naturalistic")]
        # The matrix cell reflects only the pooled provenance effect (0.2),
        # never the larger position effect (0.4) -- position never leaks in.
        assert matrix["Claude"]["ChatGPT"] == pytest.approx(0.2)


# ---------------------------------------------------------------------------
# build_provenance_matrix / matrix_csv_rows: shape and defaults
# ---------------------------------------------------------------------------

def test_matrix_covers_all_four_labels_with_zero_diagonal_even_for_unmeasured_contrasts():
    obs = make_full_block("m", "naturalistic", "provenance_claude_vs_chatgpt", "s1", "s2",
                           fwd_a=10, fwd_b=10, flp_a=0, flp_b=0)
    _, by_contrast_rows, _, _ = pipeline(obs)
    matrix = alp.build_provenance_matrix(by_contrast_rows)[("m", "naturalistic")]

    assert set(matrix) == {"Claude", "ChatGPT", "Gemini", "DeepSeek"}
    for name in matrix:
        assert matrix[name][name] == 0.0
    # Gemini/DeepSeek never appeared in any observation -- their cells default
    # to 0.0 rather than raising, since pairwise_effects.csv (not the matrix)
    # is the source of truth for whether a cell was actually measured.
    assert matrix["Gemini"]["DeepSeek"] == 0.0


def test_matrix_csv_rows_produces_sixteen_tidy_rows_for_one_model_regime():
    obs = make_full_block("m", "naturalistic", "provenance_claude_vs_chatgpt", "s1", "s2",
                           fwd_a=10, fwd_b=10, flp_a=0, flp_b=0)
    _, by_contrast_rows, matrices, _ = pipeline(obs)
    rows = alp.matrix_csv_rows(matrices)
    assert len(rows) == 16  # 4x4, including the zero diagonal
    assert {"model", "evaluation_regime", "row_label", "column_label", "directional_effect"} <= set(rows[0])


# ---------------------------------------------------------------------------
# model_regime_keys: distinct, sorted (model, evaluation_regime) pairs
# ---------------------------------------------------------------------------

def test_model_regime_keys_are_distinct_and_sorted():
    rows = [
        {"model": "b", "evaluation_regime": "naturalistic"},
        {"model": "a", "evaluation_regime": "text_only_invariance"},
        {"model": "a", "evaluation_regime": "naturalistic"},
        {"model": "a", "evaluation_regime": "naturalistic"},  # duplicate
    ]
    assert alp.model_regime_keys(rows) == [
        ("a", "naturalistic"), ("a", "text_only_invariance"), ("b", "naturalistic"),
    ]
